name: Flask CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug path
        run: |
          pwd
          ls -la
          ls -la app
          echo "PYTHONPATH: $PYTHONPATH"

      - name: Run tests
        run: PYTHONPATH=$(pwd) pytest
